### ISSUE TITLE
Need README file

### ISSUE THREAD

**Issue by groovecoder** [riverspirit/mdn-sentinel#1]
Would like to know more about how to use this and how to potentially contribute to it.

**Comment by riverspirit** [comment]
Thanks @groovecoder. I've added a rough [README](https://github.com/riverspirit/mdn-sentinel/blob/master/README.md). I had abandoned the project because it wasn't helping much and my webhost kept stopping the script. Also teoli and wbamberg were finding and deleting spam edits much faster :)
